### ISSUE TITLE
Error: Uncaught, unspecified 'error' event.

### ISSUE THREAD

**Issue by fabdrol** [AvianFlu/ntwitter#50]
Hi ladies, gentlemen

I have a weird problem I can't seem to be able to trace. Any help is appreciated. 
This is the error I get:

events.js:50
        throw new Error("Uncaught, unspecified 'error' event.");
              ^
Error: Uncaught, unspecified 'error' event.
    at EventEmitter.emit (events.js:50:15)
    at ClientRequest.<anonymous> (/root/node/test/node_modules/ntwitter/lib/twitter.js:251:14)
    at ClientRequest.emit (events.js:67:17)
    at HTTPParser.onIncoming (http.js:1258:11)
    at HTTPParser.onHeadersComplete (http.js:102:31)
    at CleartextStream.ondata (http.js:1147:24)
    at CleartextStream._push (tls.js:367:27)
    at SecurePair.cycle (tls.js:688:20)
    at EncryptedStream.write (tls.js:122:13)
    at Socket.ondata (stream.js:38:26)

It worked on localhost, for a while. On my server it doesn't. At all.

Thanks in advance

Fabian

**Comment by fredweppes** [comment]
I am getting exactly the same error, I have installed the module from NPM an hour ago.

**Comment by fredweppes** [comment]
Fabian, is your server by any chance a Windows one?
I have tried to run my script on a Linux machine and it works fine, so this might be an OS specific issue.

**Comment by fabdrol** [comment]
@fredweppes No, it isn't. But I think I might have found the troublesome behaviour. While browsing issues I came across issue [#20](https://github.com/AvianFlu/ntwitter/issues/20) - about supporting stream reconnect behaviour and this [repo](https://github.com/horixon/immortal-ntwitter) which I hoped would help. I didn't, but it did expose the error, turned out to be HTTP error. It didn't give much more information, but I think I may have found the reason.

I streamed tweets from 97 users from Twitter. Since the streaming api is a GET request, I recon the url just got too long. Didn't really test it, since without all 97 users streaming tweets would be pretty useless. In stead I went for a client-side JS implementation to poll and fetch tweets every 60 seconds, with a random sample of 10 users (out of the 97)

**Comment by KingScooty** [comment]
I'm having exactly the same issues!

**Comment by codeofthewoosters** [comment]
Me too. Anyone with any suggestions as to where to start looking?

**Comment by KingScooty** [comment]
Turns out it's from hammering the Twitter API. nTwitter isn't catching the responses and so throws an error.

**Comment by fabdrol** [comment]
Look at my last comment. All info you need is in there

**Comment by mateodelnorte** [comment]
Shouldn't this still be an issue, in that everyone who has an http related error is going to go on a wild goose chase until an adequate number of purposeful and instructive error clauses are created to diminish the number of times an error will occur? 

I got this error because something changed with my app causing a 401 UnAuthorized to come back. The module should at least emit an error with the specific message. 

Unless I missed something, it looks like there is a stream.emit('error', 'http', response.statusCode ); line with nothing listening to it. Should the twitter object be listening and  re-emiting so that client code can handle?

**Comment by mateodelnorte** [comment]
above should read "an _unknown_ error will occur"

**Comment by nicola** [comment]
I also have the same error:

 throw new Error("Uncaught, unspecified 'error' event.");
 throw new Error("Uncaught, unspecified 'error' event.");
              ^
Error: Uncaught, unspecified 'error' event.
    at EventEmitter.emit (events.js:50:15)
    at ClientRequest.<anonymous> (/Users/io/Proj/feetshot/node_modules/ntwitter/lib/twitter.js:251:14)
    at ClientRequest.emit (events.js:67:17)
    at HTTPParser.onIncoming (http.js:1261:11)
    at HTTPParser.onHeadersComplete (http.js:102:31)
    at CleartextStream.ondata (http.js:1150:24)
    at CleartextStream._push (tls.js:375:27)
    at SecurePair.cycle (tls.js:734:20)
    at EncryptedStream.write (tls.js:130:13)
    at Socket.ondata (stream.js:38:26)

This should definitely be an open issue..

**Comment by fabnoe** [comment]
Same error here.

throw new Error("Uncaught, unspecified 'error' event.");
              ^
Error: Uncaught, unspecified 'error' event.
    at EventEmitter.emit (events.js:50:15)
    at ClientRequest.<anonymous> (/Users/..../node_modules/ntwitter/lib/twitter.js:251:14)
    at ClientRequest.emit (events.js:67:17)
    at HTTPParser.onIncoming (http.js:1261:11)
    at HTTPParser.onHeadersComplete (http.js:102:31)
    at CleartextStream.ondata (http.js:1150:24)
    at CleartextStream._push (tls.js:375:27)
    at SecurePair.cycle (tls.js:734:20)
    at EncryptedStream.write (tls.js:130:13)
    at Socket.ondata (stream.js:38:26)

**Comment by nicola** [comment]
can someone reconsider to open this issue?

**Comment by dlo** [comment]
Even if it is a Twitter bug, it should be caught and display a better error message.

**Comment by gabrielstuff** [comment]
Same here.
Would be nice to open back.

Thanks

**Comment by JGarfunkel** [comment]
You could add the listener where twit.stream is defined, for example:

twit.stream('bad/url',{'track': 'nodejs'}, function(stream) {
  stream.on('data', function(data) {
    console.log(data);
  });

  stream.on('error', function(error, code) {
    console.log("My error: " + error + ": " + code);
  });

});

The catch is that the programmer would like to know what URL was the cause, and that's not emitted (since URL isn't in the response object).

If unit-testing, you could output the url within twitter.js... but that's not scalable.

**Comment by funston** [comment]
is there a solution? i get this 100% of the time, with zero volume on the api call, just initial setup to the stream url

**Comment by fabdrol** [comment]
I ended up building a custom implementation of the stream parser (lib/parser.js), which emits a lot of different events. Then I wrote a class which invokes ntwitter, catches errors, timeouts and other exceptions and reconnects when necessary - or backs off according to Twitter's rules. It's been running for months now - without interruption, and an average of between 5 - 20 tweets per second. No problem at all. 

It's quite custom so it doesn't really make sense to post the code here, but put simply there are a few things I'm checking:
- first of all, I'm actively listening to heartbeats, if I miss more than 5 it reconnects after 3 seconds
- I listen to every "non-positive" event (ie, errors and exceptions), and count them. If they fit Twitter's back-off rules, I back-off accordingly, if not, I reconnect after a delay
- I check every error wether it's actually an error: ntwitter tends to emit valid tweets as errors sometimes
- If I receive more then 5 JSON parsing errors in a row, I disconnect and reconnect after a delay (I assume packet corruption)
- Finally, if I don't receive any tweet for more than 10 minutes, I sleep a couple of seconds and reconnect.

**Comment by mateodelnorte** [comment]
Sounds pretty cool. If it's not proprietary, I'd love to see a gist.

**Comment by kuanjava** [comment]
Hi,

I've got the same error.

response code: 401

events.js:73
        throw new Error("Uncaught, unspecified 'error' event.");
              ^
Error: Uncaught, unspecified 'error' event.
    at EventEmitter.emit (events.js:73:15)
    at ClientRequest.Twitter.stream (/usr/local/lib/node_modules/ntwitter/lib/twitter.js:252:14)
    at ClientRequest.EventEmitter.emit (events.js:96:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming](http.js:1462:7)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:111:23)
    at CleartextStream.socketOnData [as ondata](http.js:1367:20)
    at CleartextStream.CryptoStream._push (tls.js:526:27)
    at SecurePair.cycle (tls.js:880:20)
    at EncryptedStream.CryptoStream.write (tls.js:267:13)
    at Socket.ondata (stream.js:38:26)

**Comment by kuanjava** [comment]
Hi,

My problem is resolved.

response code:401

Root Cause: the system clock is NOT sync.

sync system clock and then there's NO ERROR occurred.

---

onException:401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. 

Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.

---

Thank you.

Regards,
Thomas Lee

**Comment by andefined** [comment]
I agree with @kuanjava just sync your server's clock ant it works.

# yum install ntp

# chkconfig ntpd on

# ntpdate pool.ntp.org

# /etc/init.d/ntpd start

start your app again and it works!

**Comment by BrahimLee** [comment]
how can we sync the server's clock?

**Comment by andefined** [comment]
login as root to your server via ssh and use the following commands
yum install ntp
chkconfig ntpd on
ntupdate pool.ntp.org
ntpd start

read more http://www.cyberciti.biz/tips/synchronize-the-system-clock-to-network-time-protocol-ntp-under-fedora-or-red-hat-linux.html

**Comment by ghost** [comment]
I am getting this issue on an Ubuntu server.  I have synced the server's clock but I still get this typeerror.  Anybody else still having this issue or another solution?
